[2024-12-15T12:53:46.404+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T12:53:46.411+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK1.ExecuteNotebook manual__2024-12-15T12:53:44.390895+00:00 [queued]>
[2024-12-15T12:53:46.414+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK1.ExecuteNotebook manual__2024-12-15T12:53:44.390895+00:00 [queued]>
[2024-12-15T12:53:46.415+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-15T12:53:46.419+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ExecuteNotebook> on 2024-12-15 12:53:44.390895+00:00
[2024-12-15T12:53:46.422+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=28754) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-15T12:53:46.422+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'PRCS_TEST_FRAMEWORK1', 'ExecuteNotebook', 'manual__2024-12-15T12:53:44.390895+00:00', '--job-id', '1863', '--raw', '--subdir', 'DAGS_FOLDER/script/PRCS_TEST_FRAMEWORK1.py', '--cfg-path', '/tmp/tmpm70zqduv']
[2024-12-15T12:53:46.424+0000] {standard_task_runner.py:72} INFO - Started process 28770 to run task
[2024-12-15T12:53:46.424+0000] {standard_task_runner.py:105} INFO - Job 1863: Subtask ExecuteNotebook
[2024-12-15T12:53:46.444+0000] {task_command.py:467} INFO - Running <TaskInstance: PRCS_TEST_FRAMEWORK1.ExecuteNotebook manual__2024-12-15T12:53:44.390895+00:00 [running]> on host 6418ebfba5fb
[2024-12-15T12:53:46.473+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test-framework' AIRFLOW_CTX_DAG_ID='PRCS_TEST_FRAMEWORK1' AIRFLOW_CTX_TASK_ID='ExecuteNotebook' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T12:53:44.390895+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T12:53:44.390895+00:00'
[2024-12-15T12:53:46.474+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T12:53:46.481+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-15T12:53:46.488+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-15T12:53:46.491+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-15T12:53:46.495+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T12:53:46.495+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=PRCS_TEST_FRAMEWORK1, task_id=ExecuteNotebook, run_id=manual__2024-12-15T12:53:44.390895+00:00, execution_date=20241215T125344, start_date=20241215T125346, end_date=20241215T125346
[2024-12-15T12:53:46.522+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-15T12:53:46.530+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-15T12:53:46.530+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
