[2024-12-15T14:14:46.556+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T14:14:46.561+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK1.ExecuteNotebook manual__2024-12-15T14:05:55.786934+00:00 [queued]>
[2024-12-15T14:14:46.563+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK1.ExecuteNotebook manual__2024-12-15T14:05:55.786934+00:00 [queued]>
[2024-12-15T14:14:46.564+0000] {taskinstance.py:2866} INFO - Starting attempt 5 of 10
[2024-12-15T14:14:46.568+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ExecuteNotebook> on 2024-12-15 14:05:55.786934+00:00
[2024-12-15T14:14:46.571+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2570) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-15T14:14:46.572+0000] {standard_task_runner.py:72} INFO - Started process 2581 to run task
[2024-12-15T14:14:46.571+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'PRCS_TEST_FRAMEWORK1', 'ExecuteNotebook', 'manual__2024-12-15T14:05:55.786934+00:00', '--job-id', '1922', '--raw', '--subdir', 'DAGS_FOLDER/script/PRCS_TEST_FRAMEWORK1.py', '--cfg-path', '/tmp/tmputjlmlye']
[2024-12-15T14:14:46.572+0000] {standard_task_runner.py:105} INFO - Job 1922: Subtask ExecuteNotebook
[2024-12-15T14:14:46.587+0000] {task_command.py:467} INFO - Running <TaskInstance: PRCS_TEST_FRAMEWORK1.ExecuteNotebook manual__2024-12-15T14:05:55.786934+00:00 [running]> on host e12d581ca20f
[2024-12-15T14:14:46.613+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test-framework' AIRFLOW_CTX_DAG_ID='PRCS_TEST_FRAMEWORK1' AIRFLOW_CTX_TASK_ID='ExecuteNotebook' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T14:05:55.786934+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T14:05:55.786934+00:00'
[2024-12-15T14:14:46.614+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T14:14:46.621+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-15T14:14:54.821+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-15T14:14:54.826+0000] {logging_mixin.py:190} INFO - http://localhost:8888/notebooks/Log_output/PRCS_TEST_FRAMEWORK1/test1_executed.ipynb
[2024-12-15T14:14:54.826+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-15T14:14:54.829+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T14:14:54.829+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=PRCS_TEST_FRAMEWORK1, task_id=ExecuteNotebook, run_id=manual__2024-12-15T14:05:55.786934+00:00, execution_date=20241215T140555, start_date=20241215T141446, end_date=20241215T141454
[2024-12-15T14:14:54.872+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-15T14:14:54.878+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-15T14:14:54.878+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
