[2024-12-15T13:16:33.344+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T13:16:33.350+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK1.ExecuteNotebook manual__2024-12-15T13:16:31.340521+00:00 [queued]>
[2024-12-15T13:16:33.353+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK1.ExecuteNotebook manual__2024-12-15T13:16:31.340521+00:00 [queued]>
[2024-12-15T13:16:33.354+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-15T13:16:33.358+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ExecuteNotebook> on 2024-12-15 13:16:31.340521+00:00
[2024-12-15T13:16:33.363+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=33122) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-15T13:16:33.363+0000] {standard_task_runner.py:72} INFO - Started process 33137 to run task
[2024-12-15T13:16:33.363+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'PRCS_TEST_FRAMEWORK1', 'ExecuteNotebook', 'manual__2024-12-15T13:16:31.340521+00:00', '--job-id', '1879', '--raw', '--subdir', 'DAGS_FOLDER/script/PRCS_TEST_FRAMEWORK1.py', '--cfg-path', '/tmp/tmp_zd21xa0']
[2024-12-15T13:16:33.364+0000] {standard_task_runner.py:105} INFO - Job 1879: Subtask ExecuteNotebook
[2024-12-15T13:16:33.382+0000] {task_command.py:467} INFO - Running <TaskInstance: PRCS_TEST_FRAMEWORK1.ExecuteNotebook manual__2024-12-15T13:16:31.340521+00:00 [running]> on host 6418ebfba5fb
[2024-12-15T13:16:33.411+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test-framework' AIRFLOW_CTX_DAG_ID='PRCS_TEST_FRAMEWORK1' AIRFLOW_CTX_TASK_ID='ExecuteNotebook' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T13:16:31.340521+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T13:16:31.340521+00:00'
[2024-12-15T13:16:33.411+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T13:16:33.418+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-15T13:16:33.424+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-15T13:16:33.428+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-15T13:16:33.432+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T13:16:33.434+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=PRCS_TEST_FRAMEWORK1, task_id=ExecuteNotebook, run_id=manual__2024-12-15T13:16:31.340521+00:00, execution_date=20241215T131631, start_date=20241215T131633, end_date=20241215T131633
[2024-12-15T13:16:33.465+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-15T13:16:33.472+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-15T13:16:33.473+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
