[2024-11-18T17:59:40.670+0000] {processor.py:186} INFO - Started process (PID=21336) to work on /opt/airflow/dags/script/app.py
[2024-11-18T17:59:40.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T17:59:40.671+0000] {logging_mixin.py:190} INFO - [2024-11-18T17:59:40.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T17:59:40.677+0000] {logging_mixin.py:190} INFO - [2024-11-18T17:59:40.675+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 7, in <module>
    from ..framework.dwh import Framework
ImportError: attempted relative import with no known parent package
[2024-11-18T17:59:40.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T17:59:40.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.022 seconds
[2024-11-18T18:00:10.987+0000] {processor.py:186} INFO - Started process (PID=21672) to work on /opt/airflow/dags/script/app.py
[2024-11-18T18:00:10.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T18:00:10.990+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:00:10.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T18:00:11.002+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:00:11.001+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 7, in <module>
    from ..framework.dwh import Framework
ImportError: attempted relative import with no known parent package
[2024-11-18T18:00:11.003+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T18:00:11.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.038 seconds
[2024-11-18T18:01:08.233+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/script/app.py
[2024-11-18T18:01:08.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T18:01:08.236+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:01:08.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T18:01:08.239+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:01:08.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 7, in <module>
    from ..framework.dwh import Framework
ImportError: attempted relative import with no known parent package
[2024-11-18T18:01:08.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T18:01:08.258+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.028 seconds
[2024-11-18T18:01:38.801+0000] {processor.py:186} INFO - Started process (PID=524) to work on /opt/airflow/dags/script/app.py
[2024-11-18T18:01:38.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T18:01:38.806+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:01:38.805+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T18:01:38.811+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:01:38.810+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 7, in <module>
    from ..framework.dwh import Framework
ImportError: attempted relative import with no known parent package
[2024-11-18T18:01:38.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T18:01:38.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.029 seconds
[2024-11-18T18:02:09.482+0000] {processor.py:186} INFO - Started process (PID=880) to work on /opt/airflow/dags/script/app.py
[2024-11-18T18:02:09.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T18:02:09.486+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:02:09.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T18:02:09.490+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:02:09.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 7, in <module>
    from ..framework.dwh import Framework
ImportError: attempted relative import with no known parent package
[2024-11-18T18:02:09.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T18:02:09.502+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.024 seconds
[2024-11-18T18:02:40.315+0000] {processor.py:186} INFO - Started process (PID=1236) to work on /opt/airflow/dags/script/app.py
[2024-11-18T18:02:40.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T18:02:40.321+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:02:40.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T18:02:40.324+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:02:40.323+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 7, in <module>
    from ..framework.dwh import Framework
ImportError: attempted relative import with no known parent package
[2024-11-18T18:02:40.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T18:02:40.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.028 seconds
[2024-11-18T18:03:10.983+0000] {processor.py:186} INFO - Started process (PID=1592) to work on /opt/airflow/dags/script/app.py
[2024-11-18T18:03:10.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T18:03:10.989+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:03:10.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T18:03:10.992+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:03:10.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 7, in <module>
    from ..framework.dwh import Framework
ImportError: attempted relative import with no known parent package
[2024-11-18T18:03:10.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T18:03:11.004+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.026 seconds
[2024-11-18T18:03:27.403+0000] {processor.py:186} INFO - Started process (PID=1942) to work on /opt/airflow/dags/script/app.py
[2024-11-18T18:03:27.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T18:03:27.406+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:03:27.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T18:03:27.409+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:03:27.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 33
    Execute_python = BashOperator(
    ^^^^^^^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 27
[2024-11-18T18:03:27.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T18:03:27.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.022 seconds
[2024-11-18T18:03:32.471+0000] {processor.py:186} INFO - Started process (PID=1953) to work on /opt/airflow/dags/script/app.py
[2024-11-18T18:03:32.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T18:03:32.473+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:03:32.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T18:03:32.477+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:03:32.476+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 7, in <module>
    from ..framework.dwh import Framework
ImportError: attempted relative import with no known parent package
[2024-11-18T18:03:32.477+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T18:03:32.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.021 seconds
[2024-11-18T18:03:35.506+0000] {processor.py:186} INFO - Started process (PID=1958) to work on /opt/airflow/dags/script/app.py
[2024-11-18T18:03:35.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T18:03:35.508+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:03:35.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T18:03:35.511+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:03:35.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 7, in <module>
    from ..framework.dwh import Framework
ImportError: attempted relative import with no known parent package
[2024-11-18T18:03:35.511+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T18:03:35.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.017 seconds
[2024-11-18T18:03:36.535+0000] {processor.py:186} INFO - Started process (PID=1963) to work on /opt/airflow/dags/script/app.py
[2024-11-18T18:03:36.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T18:03:36.537+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:03:36.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T18:03:36.540+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:03:36.540+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 7, in <module>
    from ..framework.dwh import Framework
ImportError: attempted relative import with no known parent package
[2024-11-18T18:03:36.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T18:03:36.548+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.016 seconds
[2024-11-18T18:04:07.158+0000] {processor.py:186} INFO - Started process (PID=2319) to work on /opt/airflow/dags/script/app.py
[2024-11-18T18:04:07.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T18:04:07.160+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:04:07.160+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T18:04:07.163+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:04:07.162+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 7, in <module>
    from ..framework.dwh import Framework
ImportError: attempted relative import with no known parent package
[2024-11-18T18:04:07.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T18:04:07.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.016 seconds
[2024-11-18T18:04:37.716+0000] {processor.py:186} INFO - Started process (PID=2675) to work on /opt/airflow/dags/script/app.py
[2024-11-18T18:04:37.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T18:04:37.720+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:04:37.719+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T18:04:37.724+0000] {logging_mixin.py:190} INFO - [2024-11-18T18:04:37.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 7, in <module>
    from ..framework.dwh import Framework
ImportError: attempted relative import with no known parent package
[2024-11-18T18:04:37.724+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T18:04:37.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.026 seconds
[2024-11-18T19:32:57.349+0000] {processor.py:186} INFO - Started process (PID=18020) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:32:57.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:32:57.350+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:32:57.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:32:57.359+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:32:57.359+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:32:57.366+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:32:57.365+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:32:57.366+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:32:57.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.025 seconds
[2024-11-18T19:33:27.647+0000] {processor.py:186} INFO - Started process (PID=18376) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:33:27.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:33:27.648+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:33:27.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:33:27.658+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:33:27.658+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:33:27.676+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:33:27.675+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:33:27.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:33:27.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.039 seconds
[2024-11-18T19:33:57.828+0000] {processor.py:186} INFO - Started process (PID=18731) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:33:57.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:33:57.829+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:33:57.829+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:33:57.843+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:33:57.842+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:33:57.850+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:33:57.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:33:57.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:33:57.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.032 seconds
[2024-11-18T19:34:27.944+0000] {processor.py:186} INFO - Started process (PID=19087) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:34:27.944+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:34:27.945+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:34:27.945+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:34:27.956+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:34:27.956+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:34:27.962+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:34:27.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:34:27.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:34:27.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.026 seconds
[2024-11-18T19:34:58.158+0000] {processor.py:186} INFO - Started process (PID=19443) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:34:58.158+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:34:58.159+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:34:58.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:34:58.169+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:34:58.169+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:34:58.175+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:34:58.174+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:34:58.175+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:34:58.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.025 seconds
[2024-11-18T19:35:28.380+0000] {processor.py:186} INFO - Started process (PID=19799) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:35:28.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:35:28.382+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:35:28.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:35:28.395+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:35:28.395+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:35:28.402+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:35:28.401+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:35:28.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:35:28.407+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.032 seconds
[2024-11-18T19:35:58.649+0000] {processor.py:186} INFO - Started process (PID=20155) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:35:58.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:35:58.651+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:35:58.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:35:58.664+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:35:58.664+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:35:58.673+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:35:58.672+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:35:58.673+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:35:58.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.034 seconds
[2024-11-18T19:36:28.992+0000] {processor.py:186} INFO - Started process (PID=20511) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:36:28.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:36:28.994+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:36:28.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:36:29.013+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:36:29.013+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:36:29.025+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:36:29.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:36:29.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:36:29.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.044 seconds
[2024-11-18T19:36:59.264+0000] {processor.py:186} INFO - Started process (PID=20867) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:36:59.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:36:59.266+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:36:59.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:36:59.279+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:36:59.278+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:36:59.286+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:36:59.285+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:36:59.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:36:59.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.033 seconds
[2024-11-18T19:37:29.472+0000] {processor.py:186} INFO - Started process (PID=21223) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:37:29.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:37:29.474+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:37:29.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:37:29.487+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:37:29.486+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:37:29.495+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:37:29.494+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:37:29.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:37:29.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.033 seconds
[2024-11-18T19:38:00.008+0000] {processor.py:186} INFO - Started process (PID=21579) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:38:00.009+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:38:00.010+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:38:00.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:38:00.022+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:38:00.022+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:38:00.029+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:38:00.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:38:00.030+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:38:00.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.031 seconds
[2024-11-18T19:38:30.382+0000] {processor.py:186} INFO - Started process (PID=21945) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:38:30.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:38:30.383+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:38:30.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:38:30.390+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:38:30.390+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:38:30.395+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:38:30.394+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:38:30.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:38:30.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.020 seconds
[2024-11-18T19:39:00.544+0000] {processor.py:186} INFO - Started process (PID=22301) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:39:00.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:39:00.545+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:39:00.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:39:00.552+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:39:00.552+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:39:00.559+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:39:00.558+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:39:00.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:39:00.563+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.021 seconds
[2024-11-18T19:39:30.717+0000] {processor.py:186} INFO - Started process (PID=22657) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:39:30.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:39:30.718+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:39:30.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:39:30.730+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:39:30.730+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:39:30.738+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:39:30.737+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:39:30.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:39:30.744+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.032 seconds
[2024-11-18T19:40:01.034+0000] {processor.py:186} INFO - Started process (PID=23023) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:40:01.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:40:01.036+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:40:01.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:40:01.048+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:40:01.047+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:40:01.056+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:40:01.055+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:40:01.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:40:01.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.032 seconds
[2024-11-18T19:40:31.323+0000] {processor.py:186} INFO - Started process (PID=23379) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:40:31.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:40:31.324+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:40:31.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:40:31.337+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:40:31.337+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:40:31.345+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:40:31.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:40:31.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:40:31.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.033 seconds
[2024-11-18T19:41:01.734+0000] {processor.py:186} INFO - Started process (PID=23735) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:41:01.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:41:01.736+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:41:01.736+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:41:01.747+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:41:01.747+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:41:01.756+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:41:01.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:41:01.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:41:01.761+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.032 seconds
[2024-11-18T19:41:31.964+0000] {processor.py:186} INFO - Started process (PID=24091) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:41:31.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:41:31.966+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:41:31.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:41:31.981+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:41:31.980+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:41:31.991+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:41:31.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:41:31.991+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:41:31.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.037 seconds
[2024-11-18T19:42:02.221+0000] {processor.py:186} INFO - Started process (PID=24447) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:42:02.222+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:42:02.223+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:42:02.223+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:42:02.236+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:42:02.235+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:42:02.245+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:42:02.244+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:42:02.245+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:42:02.252+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.036 seconds
[2024-11-18T19:42:32.517+0000] {processor.py:186} INFO - Started process (PID=24803) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:42:32.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:42:32.519+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:42:32.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:42:32.533+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:42:32.532+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:42:32.540+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:42:32.539+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:42:32.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:42:32.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.033 seconds
[2024-11-18T19:43:02.915+0000] {processor.py:186} INFO - Started process (PID=25159) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:43:02.916+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:43:02.917+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:43:02.917+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:43:02.930+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:43:02.929+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:43:02.937+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:43:02.936+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:43:02.938+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:43:02.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.032 seconds
[2024-11-18T19:43:33.268+0000] {processor.py:186} INFO - Started process (PID=25525) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:43:33.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:43:33.269+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:43:33.269+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:43:33.281+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:43:33.281+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:43:33.288+0000] {logging_mixin.py:190} INFO - {}
[2024-11-18T19:43:33.289+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:43:33.288+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 139, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:43:33.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:43:33.294+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.030 seconds
[2024-11-18T19:44:03.725+0000] {processor.py:186} INFO - Started process (PID=25884) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:44:03.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:44:03.727+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:44:03.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:44:03.741+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:44:03.741+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:44:03.749+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:44:03.747+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    print(config_data.strem_nm)
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'strem_nm'
[2024-11-18T19:44:03.749+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:44:03.754+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.033 seconds
[2024-11-18T19:44:34.034+0000] {processor.py:186} INFO - Started process (PID=26247) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:44:34.034+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:44:34.035+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:44:34.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:44:34.048+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:44:34.048+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:44:34.058+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:44:34.057+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    print(type(config_data.strem_nm))
               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'strem_nm'
[2024-11-18T19:44:34.059+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:44:34.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.036 seconds
[2024-11-18T19:45:04.374+0000] {processor.py:186} INFO - Started process (PID=26608) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:45:04.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:45:04.376+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:45:04.376+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:45:04.388+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:45:04.388+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:45:04.394+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:45:04.393+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    print(type(config_data['strem_nm']))
               ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:45:04.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:45:04.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.030 seconds
[2024-11-18T19:45:34.565+0000] {processor.py:186} INFO - Started process (PID=26964) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:45:34.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:45:34.567+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:45:34.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:45:34.579+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:45:34.579+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:45:34.588+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:45:34.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 138, in get_controller
    print(type(config_data['strem_nm']))
               ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:45:34.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:45:34.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.032 seconds
[2024-11-18T19:46:04.982+0000] {processor.py:186} INFO - Started process (PID=27330) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:46:04.982+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:46:04.983+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:46:04.983+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:46:04.996+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:46:04.996+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:46:05.002+0000] {logging_mixin.py:190} INFO - <class 'dict'>
[2024-11-18T19:46:05.004+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:46:05.003+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 139, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:46:05.004+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:46:05.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.032 seconds
[2024-11-18T19:46:35.310+0000] {processor.py:186} INFO - Started process (PID=27686) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:46:35.310+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:46:35.312+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:46:35.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:46:35.329+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:46:35.329+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:46:35.339+0000] {logging_mixin.py:190} INFO - <class 'dict'>
[2024-11-18T19:46:35.340+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:46:35.339+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 139, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:46:35.341+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:46:35.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.043 seconds
[2024-11-18T19:47:05.803+0000] {processor.py:186} INFO - Started process (PID=28042) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:47:05.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:47:05.806+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:47:05.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:47:05.820+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:47:05.820+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:47:05.828+0000] {logging_mixin.py:190} INFO - <class 'dict'>
[2024-11-18T19:47:05.830+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:47:05.828+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 139, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:47:05.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:47:05.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.038 seconds
[2024-11-18T19:47:36.035+0000] {processor.py:186} INFO - Started process (PID=28398) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:47:36.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:47:36.037+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:47:36.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:47:36.047+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:47:36.047+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:47:36.053+0000] {logging_mixin.py:190} INFO - <class 'dict'>
[2024-11-18T19:47:36.054+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:47:36.053+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 139, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:47:36.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:47:36.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.027 seconds
[2024-11-18T19:48:06.380+0000] {processor.py:186} INFO - Started process (PID=28754) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:48:06.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:48:06.381+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:48:06.381+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:48:06.393+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:48:06.393+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:48:06.400+0000] {logging_mixin.py:190} INFO - <class 'dict'>
[2024-11-18T19:48:06.401+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:48:06.400+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 139, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:48:06.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:48:06.407+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.031 seconds
[2024-11-18T19:48:36.771+0000] {processor.py:186} INFO - Started process (PID=29110) to work on /opt/airflow/dags/script/app.py
[2024-11-18T19:48:36.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/script/app.py for tasks to queue
[2024-11-18T19:48:36.773+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:48:36.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/script/app.py
[2024-11-18T19:48:36.787+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:48:36.787+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-11-18T19:48:36.793+0000] {logging_mixin.py:190} INFO - <class 'dict'>
[2024-11-18T19:48:36.795+0000] {logging_mixin.py:190} INFO - [2024-11-18T19:48:36.794+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/script/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/script/app.py", line 17, in <module>
    controller = Framework.get_controller(process_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 139, in get_controller
    return Framework.InitController(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/framework/dwh.py", line 80, in __init__
    super().__init__(args)
  File "/opt/airflow/dags/framework/dwh.py", line 55, in __init__
    self.strem_nm = args['strem_nm']
                    ~~~~^^^^^^^^^^^^
KeyError: 'strem_nm'
[2024-11-18T19:48:36.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/script/app.py
[2024-11-18T19:48:36.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/script/app.py took 0.033 seconds
